### ISSUE TITLE
Not Emacs

### ISSUE THREAD

**Issue by bengcooper** [rob-a-bolton/apm-userscript#1]
Hi! Great work, thanks for contributing to the open source community!

There's one minor bug though - I'm an Emacs user and this doesn't work in Emacs. Can you fix it please?

Thanks! :smiley:

**Comment by LewisDaleUK** [comment]
+1 for Vim too

**Comment by bengcooper** [comment]
Closing because it's a new year and I'm forgiving people and wiping the slate clean
